# Generated by Django 4.1.7 on 2023-04-08 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('gender', models.CharField(blank=True, max_length=25)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('user_type', models.CharField(choices=[('as_a', 'AS A'), ('user', 'USER'), ('mechanic', 'MECHANIC'), ('fual_station', 'FUAL STATION')], default='as_a', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
