# Generated by Django 4.1.7 on 2023-04-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_state_rename_city_name_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='districtid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.districts'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.state'),
        ),
        migrations.AlterField(
            model_name='districts',
            name='state_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.state'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.city'),
        ),
    ]
