# Generated by Django 4.1.7 on 2023-04-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_city_districtid_alter_city_state_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Districts',
            new_name='District',
        ),
    ]
