# Generated by Django 4.1.7 on 2023-04-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_districts_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='districtid',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='state_id',
            new_name='state',
        ),
    ]
