# Generated by Django 4.1.7 on 2023-04-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_district_state_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/profile.png', upload_to='photos/%Y/%m/%d'),
        ),
    ]
