# Generated by Django 4.1.7 on 2023-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_detailservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailservice',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
