# Generated by Django 4.1.7 on 2023-04-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_detailservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailservice',
            name='lang',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detailservice',
            name='lat',
            field=models.CharField(max_length=50),
        ),
    ]
