# Generated by Django 4.1.7 on 2023-04-13 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_alter_detailservice_lang_alter_detailservice_lat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detailservice',
            new_name='ServiceProvider',
        ),
    ]
