# Generated by Django 4.1.7 on 2023-04-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('Approved', 'APPROVED'), ('deliver_fuel', 'DELIVER FUEL'), ('completed_service', 'COMPLETED SERVICE')], default='pending', max_length=50),
        ),
    ]
