# Generated by Django 4.1.7 on 2023-04-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_booking_sprovider_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default=0, max_length=5, verbose_name='(STATUS)0=pending, 1 = accepted, 2 = rejected, 3 = completed'),
        ),
    ]
