# Generated by Django 4.1.7 on 2023-04-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('Approved', 'APPROVED'), ('reject', 'REJECT'), ('Deliver_fuel', 'DELIVER FUEL'), ('Completed_service', 'COMPLETED SERVICE')], default='pending', max_length=50),
        ),
    ]
